"""create tables

Revision ID: e4244e10d666
Revises: 
Create Date: 2026-05-05 11:08:04.517447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4244e10d666'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'courtier', 'acheteur', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('oaciq_number', sa.String(length=50), nullable=True),
    sa.Column('agency_name', sa.String(length=255), nullable=True),
    sa.Column('convention_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_qualified', sa.Boolean(), nullable=False),
    sa.Column('engagement_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('courtier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'analyse', 'bid', 'intro', 'pa_signed', 'nogo', name='dealstatus'), nullable=False),
    sa.Column('property_type', sa.Enum('multiplex', 'commercial', 'mixte', 'industriel', 'terrain', name='propertytype'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address_private', sa.String(length=500), nullable=False),
    sa.Column('asking_price', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.Integer(), nullable=True),
    sa.Column('yield_pct', sa.Float(), nullable=True),
    sa.Column('num_units', sa.Integer(), nullable=True),
    sa.Column('teaser_text', sa.Text(), nullable=True),
    sa.Column('full_report_path', sa.String(length=500), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('bid_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nogo_reason', sa.Text(), nullable=True),
    sa.Column('fee_pct', sa.Float(), nullable=True),
    sa.Column('fee_minimum', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['courtier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('acheteur_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'winner', 'loser', 'withdrawn', name='bidstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'deposit_sent', 'deposit_confirmed', 'balance_sent', 'paid', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('interac_ref', sa.String(length=100), nullable=True),
    sa.Column('watermarked_path', sa.String(length=500), nullable=True),
    sa.Column('engagement_signed', sa.Boolean(), nullable=False),
    sa.Column('engagement_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acheteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_type', sa.Enum('nouveau_deal', 'nda_signee', 'bid_soumis', 'fermeture_gagnant', 'fermeture_perdants', 'depot_confirme', 'verdict_go', 'verdict_nogo', 'pa_signee', name='emailtype'), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('resend_id', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ndas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('acheteur_id', sa.UUID(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acheteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ndas')
    op.drop_table('email_logs')
    op.drop_table('bids')
    op.drop_table('deals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
